name: CI
on:
  push:
    branches: [ master ]

  # Alias never.
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: make check
